Validate verification code input before sending it
SURFscz/pam-weblogin pull request #103
Opened 2024-10-17 12:49 UTC by marlam

This makes sure that the verification code only contains characters a-z A-Z 0-9, and is of limited length.

Otherwise it is possible for a user to cause arbitrary data to be sent to the server, including invalid JSON. This could be a problem if the JSON parser on the receiving end has bugs.

For example, code input 'A"}BBBBBBBB...' would lead to JSON data '{"session_id":"SESSIONID","pin":"A"}BBBBBBBB..."}' to be sent to the server.

2024-10-18 07:52 UTC, mrvanes commented
When using pamtester to test the PR, I get a segmentation fault on and empty code response:
```
Enter verification code: <enter>
Segmentation fault
```

It would be nice if you could extend the validation to the username input and return a `permission denied` on invalid usernames:
```
$ sudo pamtester weblogin '"a}aaa"' authenticate
Server error!
pamtester: System error
```

2024-10-18 08:27 UTC, marlam commented
I fixed the segfault - I overlooked that tty_input() returns NULL on empty input.

This can also bite the group input, I opened PR #104 for this.

I will extent this to cover user names in a separate PR, because that requires a small extension of `input_is_safe()`.

2024-11-01 15:42 UTC, baszoetekouw requested changes
Hi Martin!
Thanks for this PR.  Looks good in principle, but I think we should be a bit more careful with the string manipulations (see comments).

2024-11-01 15:42 UTC, baszoetekouw commented on src/tty.c
> +	size_t length = strlen(input);
This is not safe.  If input isn't terminated by a `\0`, strlen() will run into unrelated memory.  This is unlikely but could possibly occur.

The better solution is to use `strnlen()` and then make sure that the string is 0-terminated.  Or use `strndup()` to make a local copy of the string.

2024-11-01 15:42 UTC, baszoetekouw commented on src/tty.c
> +int input_is_safe(const char *input, size_t max_length)
If you intend to return a true/false value, please use an explicit `bool` value for that.

2024-11-13 14:33 UTC, baszoetekouw approved these changes

2024-11-13 14:34 UTC, merged